services:
  db:
    ports:
      - "5432:5432"
    volumes:
      - vio-tune-data:/var/lib/postgresql/data
      - ./dumps:/dumps

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - db

  app:
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"